FROM osixia/openldap:1.5.0


ENV LDAP_ORGANISATION="Al-waleed Test Org" \ 
    LDAP_DOMAIN="kpbookstore.kp"

COPY bootstrap.ldif /container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif