FROM node:18-alpine3.14 AS builder

WORKDIR /app

COPY ./package.json ./yarn.lock ./

# Mustn't be only --production, because nest-cli is a dev-dependecy, and only nest can build a production version!
RUN yarn --exact && yarn list

COPY . .

# Generate the prisma rust binary (ORM)
RUN yarn prisma generate

# Generate production files 
RUN yarn build

RUN rm .env

RUN cp .env.production .env

RUN apk --no-cache add curl

EXPOSE 8080

CMD [ "yarn", "start:prod" ]
